### ISSUE TITLE
How to deal with subjects or objects that appear multiple times in the text？

### ISSUE THREAD

**Issue by liuyijiang1994** [neukg/GRTE#2]
Thanks for your wonderful work!
I have a question. Since there is only text of subject and object in the dataset and there is no location information, is the first found location used as the subject or object when reading data?
We look forward to your reply!

**Comment by liuyijiang1994** [comment]
In addition, we note that in some datasets (e.g. NYT24 train.json), there are some following instances:
```
{
        "text": "She has played Edith Piaf in a one-woman show seen in the United States and France , and possesses some of Piaf 's spirit as well as the throbbing mixture of steel and cotton in the voice .",
        "triple_list": [
            [
                "\u00c9dith Piaf",
                "/people/person/nationality",
                "France"
            ]
        ]
    }
```
These triples don't seem to be matched by the ``search`` function in ``main.py``, how is this handled?
Thanks!

**Comment by neukg** [comment]
> Thanks for your wonderful work!
> I have a question. Since there is only text of subject and object in the dataset and there is no location information, is the first found location used as the subject or object when reading data?
> We look forward to your reply!
Yes, we take the location where the entity first appears as the correct location. Of course, there must be other, better solutions, but this is not the scope of the paper.

**Comment by neukg** [comment]
> Thanks for your wonderful work!
> I have a question. Since there is only text of subject and object in the dataset and there is no location information, is the first found location used as the subject or object when reading data?
> We look forward to your reply!

Yes, we only consider the location where the entity first appears as the standard location. There are certainly better ways of doing this, but that is beyond the scope of this article.

**Comment by neukg** [comment]
> In addition, we note that in some datasets (e.g. NYT24 train.json), there are some following instances:
> 
> ```
> {
>         "text": "She has played Edith Piaf in a one-woman show seen in the United States and France , and possesses some of Piaf 's spirit as well as the throbbing mixture of steel and cotton in the voice .",
>         "triple_list": [
>             [
>                 "\u00c9dith Piaf",
>                 "/people/person/nationality",
>                 "France"
>             ]
>         ]
>     }
> ```
> 
> These triples don't seem to be matched by the `search` function in `main.py`, how is this handled?
> Thanks!

We simply ignore the wrong triplet.

**Comment by sssssajfsd** [comment]
> In addition, we note that in some datasets (e.g. NYT24 train.json), there are some following instances:
> 
> ```
> {
>         "text": "She has played Edith Piaf in a one-woman show seen in the United States and France , and possesses some of Piaf 's spirit as well as the throbbing mixture of steel and cotton in the voice .",
>         "triple_list": [
>             [
>                 "\u00c9dith Piaf",
>                 "/people/person/nationality",
>                 "France"
>             ]
>         ]
>     }
> ```
> 
> These triples don't seem to be matched by the `search` function in `main.py`, how is this handled? Thanks!



> Thanks for your wonderful work! I have a question. Since there is only text of subject and object in the dataset and there is no location information, is the first found location used as the subject or object when reading data? We look forward to your reply!

Hi, may I ask what the version of bert4keras is

**Comment by liuyijiang1994** [comment]
> > In addition, we note that in some datasets (e.g. NYT24 train.json), there are some following instances:
> > ```
> > {
> >         "text": "She has played Edith Piaf in a one-woman show seen in the United States and France , and possesses some of Piaf 's spirit as well as the throbbing mixture of steel and cotton in the voice .",
> >         "triple_list": [
> >             [
> >                 "\u00c9dith Piaf",
> >                 "/people/person/nationality",
> >                 "France"
> >             ]
> >         ]
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These triples don't seem to be matched by the `search` function in `main.py`, how is this handled? Thanks!
> 
> > Thanks for your wonderful work! I have a question. Since there is only text of subject and object in the dataset and there is no location information, is the first found location used as the subject or object when reading data? We look forward to your reply!
> 
> Hi, may I ask what the version of bert4keras is

I didn't run the code, I just looked :(

**Comment by sssssajfsd** [comment]
> > > In addition, we note that in some datasets (e.g. NYT24 train.json), there are some following instances:
> > > ```
> > > {
> > >         "text": "She has played Edith Piaf in a one-woman show seen in the United States and France , and possesses some of Piaf 's spirit as well as the throbbing mixture of steel and cotton in the voice .",
> > >         "triple_list": [
> > >             [
> > >                 "\u00c9dith Piaf",
> > >                 "/people/person/nationality",
> > >                 "France"
> > >             ]
> > >         ]
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > These triples don't seem to be matched by the `search` function in `main.py`, how is this handled? Thanks!
> > 
> > 
> > > Thanks for your wonderful work! I have a question. Since there is only text of subject and object in the dataset and there is no location information, is the first found location used as the subject or object when reading data? We look forward to your reply!
> > 
> > 
> > Hi, may I ask what the version of bert4keras is
> 
> I didn't run the code, I just looked :(

OK,thank you!
